name: Deploy Functions (Staging)
on:
  push:
    branches: [ "staging" ]
    paths:
      - "functions/**"
      - ".github/workflows/functions-staging.yml"
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_TALE_OF_HEROS_STAGING }}
      - uses: actions/setup-node@v4
        with: { node-version: "20" }
      - run: npm i -g firebase-tools
      - run: npm ci
        working-directory: functions
      - if: hashFiles('functions/tsconfig.json') != ''
        run: npm run build
        working-directory: functions
      - run: firebase deploy --only functions --project tale-of-heros-staging
