# .github/workflows/functions-production.yml

name: Deploy Functions (Production)

on:
  push:
    branches: [ "main" ]
    paths:
      - "functions/**"
      - ".github/workflows/functions-production.yml"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v4
      
      # --- ▼▼▼ 디버깅을 위해 추가된 부분 ▼▼▼ ---
      - name: List all files to check paths
        run: ls -R
      # --- ▲▲▲ 디버깅을 위해 추가된 부분 ▲▲▲ ---

      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_TALE_OF_HEROS___FANGAME }}
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
      
      - name: Install Firebase CLI and Dependencies
        run: |
          npm install -g firebase-tools
          npm ci
        working-directory: functions
      
      - name: Build TypeScript (if needed)
        if: hashFiles('functions/tsconfig.json') != ''
        run: npm run build
        working-directory: functions

      - name: Deploy to Firebase Functions
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
        run: firebase deploy --only functions --project tale-of-heros---fangame

